# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

arch: 
- amd64
- ppc64le

os:
- linux
- osx

r:
- oldrel
- release
- devel
- 3.3.0

env:
- TravisCI=true

cache: packages
warnings_are_errors: true

matrix:
  exclude:
  - os: osx
    r: devel
  - arch: ppc64le
    os: osx
    r: oldrel
  - arch: ppc64le
    os: osx
    r: release
  - arch: ppc64le
    os: osx
    r: devel
  - arch: ppc64le
    os: osx
    r: 3.3.0

before_install:
- cd pkg
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo chown -R $(whoami) /usr/local/share/man/man7; brew install libgit2; fi

addons:
  apt:
    packages:
    - libgit2-dev

install:
- Rscript -e 'install.packages(c("roxygen2"));if (!all(c("roxygen2") %in% installed.packages())) { q(status = 1, save = "no")}' --no-init-file
- Rscript -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}' --no-init-file
- Rscript -e 'devtools::install_deps(dep = T)' --no-init-file
- Rscript -e 'devtools::document()'

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install()' --no-init-file
- Rscript -e 'devtools::test()' --no-init-file
